# Generated by Django 5.0 on 2024-01-14 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Address', models.CharField(blank=True, max_length=250, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('LandMark', models.CharField(blank=True, max_length=250, null=True)),
                ('Phone1', models.CharField(max_length=250)),
                ('Phone2', models.CharField(blank=True, max_length=250, null=True)),
                ('Gst_number', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=250)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('LandMark', models.CharField(blank=True, max_length=250, null=True)),
                ('Phone1', models.CharField(max_length=250)),
                ('Phone2', models.CharField(blank=True, max_length=250, null=True)),
                ('Gst_number', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=250)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Qty', models.IntegerField(blank=True, null=True)),
                ('Buying_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('Land_Mark', models.CharField(blank=True, max_length=250, null=True)),
                ('Address', models.CharField(blank=True, max_length=250, null=True)),
                ('Phone', models.CharField(blank=True, max_length=250, null=True)),
                ('Labour_Charge', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('Final_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labour_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Phone', models.CharField(max_length=250)),
                ('Joining_Date', models.DateField(blank=True, null=True)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('available_Qty', models.IntegerField(blank=True, null=True)),
                ('sold_Qty', models.IntegerField(blank=True, null=True)),
                ('retail_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('validity', models.CharField(max_length=250)),
                ('manufacture_Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Number', models.CharField(blank=True, max_length=250, null=True)),
                ('Vehicle_Owner_Name', models.CharField(max_length=250)),
                ('Phone', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Labour_Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Salary', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('Labour_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Labour_Details', to='KeralaPachaApp.labour_details')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField(blank=True, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('Is_whole_price', models.BooleanField()),
                ('Is_discounted', models.BooleanField()),
                ('Discount', models.CharField(max_length=250)),
                ('Price_After_Discount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('Total', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('Is_Cash_On_Delivery', models.BooleanField()),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Order_Status', models.CharField(max_length=250)),
                ('Payment_Status', models.CharField(max_length=250)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer_Details', to='KeralaPachaApp.customer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Details', to='KeralaPachaApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='labour_details',
            name='Salary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Salary_Type', to='KeralaPachaApp.salary_type'),
        ),
        migrations.CreateModel(
            name='Vehicle_Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('Distance', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('Vehicle_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_Details', to='KeralaPachaApp.vehicle_details')),
            ],
        ),
    ]
