# Generated by Django 4.2.6 on 2023-12-30 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KeralaPachaApp', '0002_alter_company_address_alter_company_gst_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='item_purchased',
            name='Address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item_purchased',
            name='Land_Mark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item_purchased',
            name='Phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='labour_details',
            name='Salary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Salary_Type', to='KeralaPachaApp.salary_type'),
        ),
    ]
